export enum envEnum {
  env = 'env',
  dbPort = 'DB_PORT',
  host = 'DB_HOST',
  userName = 'DB_USERNAME',
  database = 'DB_DATABASE',
  password = 'DB_PASSWORD',
  secretKey = 'JWT_SECRET_KEY',
  jwtDuration = 'JWT_DURATION',
  slaveNum = 'DB_SLAVE_NUM',
  slaveHost = 'DB_SLAVE_HOST',
  slaveNames = 'DB_SLAVE_USERNAME',
  slavePasswords = 'DB_SLAVE_PASSWORD',
  slavePort = 'DB_SLAVE_PORT',
  slaveDatabase = 'DB_SLAVE_DATABASE',
}
